In [1]:
import numpy as np

In [2]:
vector1 = np.array([2, 4, 6])
vector2 = np.array([1, 3, 5])

print("Vector 1:", vector1)
print("Vector 2:", vector2)

Vector 1: [2 4 6]
Vector 2: [1 3 5]


In [3]:
print("Vector Addition:")
print(vector1 + vector2)

print("\nDot Product:")
print(np.dot(vector1, vector2))

Vector Addition:
[ 3  7 11]

Dot Product:
44


In [4]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

print("Matrix Multiplication:")
print(np.matmul(matrix1,matrix2))

Matrix Multiplication:
[[19 22]
 [43 50]]


In [5]:
print("Transpose:")
print(matrix1.T)

Transpose:
[[1 3]
 [2 4]]


In [6]:
values, vectors = np.linalg.eig(matrix1)

print("Eigenvalues:")
print(values)

print("\nEigenvectors:")
print(vectors)

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
